server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    schemas: public_flyway
  datasource:
    schema: classpath:db/schema.sql
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: none
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_POST:5432}/demo-db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  flyway:
    enabled: true
logging:
  level:
    root: info
    org.springframework.data.r2dbc: debug